# Copyright 2018 - aeres.io - All Rights Reserved

ROOT = $(realpath ../..)

VPATH = $(ROOT)/out/bin $(ROOT)/src/libquic/out/lib

TARGET = aeres

SPECS = aeres.spec

SOURCES = \
					aeres \
					libquic.so

include $(ROOT)/setup/rpm/Rpm.mk
